@startuml

actor A1 as "User"
actor A2 as "Client"

rectangle Database
rectangle "Search System" {
usecase UC1 as "Search Database"
usecase UCa as " Get Results"
usecase UC6 as "Start Application"
usecase UC3 as "Set Parameters"
usecase UC2 as "Enter Query"
usecase UC4 as "Analyse Report"

A1 - UC6
UC6 - UC2
UC3 - UC1
UC1 - Database

UC1 ..> UCa : include
A2 - UCa

}
usecase UC5 as "Get Requirements"
A2 - UC5
UC5 - A1
A1 - UC4
UC2 - UC3
@enduml